export type AdminNavKey =
  | "dashboard"
  | "calendar"
  | "reports"
  | "attendanceScanner"
  | "courses"
  | "courseScheduler"
  | "classTypes"
  | "classes"
  | "appointments"
  | "videos"
  | "members"
  | "membershipTypes"
  | "membershipPlans"
  | "planningInstructors"
  | "planningRooms"
  | "planningStaff"
  | "contacts"
  | "marketing"
  | "analytics"
  | "settings";

